# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sys_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

class Ui_Form(QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        Form.setMinimumSize(QtCore.QSize(500, 400))
        Form.setMaximumSize(QtCore.QSize(500, 400))
        self.log_in = QtWidgets.QPushButton(Form)
        self.log_in.setGeometry(QtCore.QRect(160, 290, 93, 28))
        self.log_in.setObjectName("log_in")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 90, 91, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.UserName = QtWidgets.QLineEdit(Form)
        self.UserName.setGeometry(QtCore.QRect(170, 100, 191, 21))
        self.UserName.setObjectName("UserName")
        self.PassWord = QtWidgets.QLineEdit(Form)
        self.PassWord.setGeometry(QtCore.QRect(170, 160, 191, 21))
        self.PassWord.setObjectName("PassWord")
        self.PassWord.setEchoMode(QLineEdit.Password)
        self.code_pic = QtWidgets.QLabel(Form)
        self.code_pic.setGeometry(QtCore.QRect(260, 190, 122, 54))
        self.code_pic.setMinimumSize(QtCore.QSize(122, 54))
        self.code_pic.setMaximumSize(QtCore.QSize(122, 54))
        self.code_pic.setText("")
        self.code_pic.setObjectName("code_pic")
        self.code_de = QtWidgets.QLineEdit(Form)
        self.code_de.setGeometry(QtCore.QRect(170, 210, 80, 21))
        self.code_de.setMinimumSize(QtCore.QSize(80, 0))
        self.code_de.setMaximumSize(QtCore.QSize(80, 16777215))
        self.code_de.setObjectName("code_de")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "成都东软学院教务系统"))
        self.log_in.setText(_translate("Form", "登录"))
        self.label.setText(_translate("Form", "用户名："))
        self.label_2.setText(_translate("Form", "密码："))
        self.label_3.setText(_translate("Form", "验证码："))

    def msg1(self):
        QMessageBox.about(self, "教务网络管理系统", "登录成功")

    def msg2(self):
        QMessageBox.about(self, "教务网络管理系统", "登录失败")